"""add episode fields

Revision ID: 18170005b613
Revises: bda9d1db905f
Create Date: 2026-08-29 22:43:29.627108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18170005b613'
down_revision: Union[str, Sequence[str], None] = 'bda9d1db905f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('episodes', sa.Column('episode_number', sa.Integer(), nullable=True))
    op.add_column('episodes', sa.Column('synopsis', sa.String(), nullable=True))
    op.add_column('episodes', sa.Column('availability', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'episodes', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episodes', type_='unique')
    op.drop_column('episodes', 'availability')
    op.drop_column('episodes', 'synopsis')
    op.drop_column('episodes', 'episode_number')
    op.drop_column('episodes', 'slug')
    # ### end Alembic commands ###
