"""add_system_settings

Revision ID: 568ceda97fd8
Revises: fb43e4083cbb
Create Date: 2026-08-30 16:15:19.045373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '568ceda97fd8'
down_revision: Union[str, Sequence[str], None] = 'fb43e4083cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=False),
    sa.Column('site_url', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('default_section', sa.String(), nullable=False),
    sa.Column('default_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_status', sa.String(), nullable=False),
    sa.Column('season_0_handling', sa.String(), nullable=False),
    sa.Column('content_grouping', sa.String(), nullable=False),
    sa.Column('auto_publish', sa.Boolean(), nullable=False),
    sa.Column('generate_backup', sa.Boolean(), nullable=False),
    sa.Column('catalogue_format', sa.String(), nullable=False),
    sa.Column('atomic_publish', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
