"""Add duration_seconds to PublishRun

Revision ID: fb43e4083cbb
Revises: 83fa60897101
Create Date: 2026-08-30 13:07:07.008520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb43e4083cbb'
down_revision: Union[str, Sequence[str], None] = '83fa60897101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_runs', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publish_runs', 'duration_seconds')
    # ### end Alembic commands ###
